# this file defines the different configurations for possible graphs based on the selected columns
configurations:
  # selected_variables: the variables that are selected by the user
  # this is used to determine which graph types are possible
  # variables can be of type: numeric, date, boolean, string, categorical
  # variables are lists because some graphs can be made with multiple types of variables
  # graph_types: the types of graphs that are possible with the selected variables
  # each graph type has a description and a list of optional variables
  # optional variables are variables that can be added to the graph and define the possible values
  # for that the dropdown list will contain

  # numeric / none
  - selected_variables:
      x_variable:
        - numeric
      y_variable:
    graph_types:
      - name: box
        description: Shows the distribution of {{x_variable}}.
        optional_variables:
          color_variable:
            types:
              - date
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
      - name: histogram
        description: Shows the distribution of {{x_variable}}.
        optional_variables:
          color_variable:
            types:
              - date
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
      - name: scatter
        description: Shows the relationship between {{x_variable}} and the index/order.
        optional_variables:
          color_variable:
            types:
              - numeric
              - date
              - boolean
              - string
              - categorical
          size_variable:
            types:
              - numeric
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
      - name: line
        description: Line graph of {{x_variable}} and the index/order.
        optional_variables:
          color_variable:
            types:
              - numeric
              - date
              - boolean
              - string
              - categorical
          size_variable:
            types:
              - numeric
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
  # none / numeric
  - selected_variables:
      x_variable:
      y_variable:
        - numeric
    graph_types:
      - name: box
        description: Shows the distribution of {{y_variable}}.
        optional_variables:
          color_variable:
            types:
              - date
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
      - name: histogram
        description: Shows the distribution of {{y_variable}}.
        optional_variables:
          color_variable:
            types:
              - date
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
      - name: scatter
        description: Shows the relationship between {{y_variable}} and the index/order.
        optional_variables:
          color_variable:
            types:
              - numeric
              - date
              - boolean
              - string
              - categorical
          size_variable:
            types:
              - numeric
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
      - name: line
        description: Line graph of {{y_variable}} and the index/order.
        optional_variables:
          color_variable:
            types:
              - numeric
              - date
              - boolean
              - string
              - categorical
          size_variable:
            types:
              - numeric
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
  # numeric / numeric
  - selected_variables:
      x_variable:
        - numeric
      y_variable:
        - numeric
    graph_types:
      - name: scatter
        description: Shows the relationship between {{x_variable}} and {{y_variable}}.
        optional_variables:
          color_variable:
            types:
              - numeric
              - date
              - boolean
              - string
              - categorical
          size_variable:
            types:
              - numeric
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
      - name: heatmap
        description: Shows the relationship between {{x_variable}} and {{y_variable}}.
        optional_variables:
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
      - name: box
        description: Shows the distribution of {{y_variable}} values across {{x_variable}} values.
        optional_variables:
          color_variable:
            types:
              - date
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
      - name: histogram
        description: Shows the distribution of the sum of {{y_variable}} values across {{x_variable}} values.
        optional_variables:
          color_variable:
            types:
              - date
              - boolean
              - string
              - categorical
              - numeric
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
  # numeric / numeric / numeric
  - selected_variables:
      x_variable:
        - numeric
      y_variable:
        - numeric
      z_variable:
        - numeric
    graph_types:
      - name: scatter-3d
        description: Shows the relationship between {{x_variable}}, {{y_variable}}, and {{z_variable}}.
        optional_variables:
          color_variable:
            types:
              - numeric
              - date
              - boolean
              - string
              - categorical
          size_variable:
            types:
              - numeric
  # non-numeric / none
  - selected_variables:
      x_variable:
        - boolean
        - string
        - categorical
      y_variable:
    graph_types:
      - name: histogram
        description: Shows the counts of {{x_variable}}.
        optional_variables:
          color_variable:
            types:
              - numeric
              - date
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
  # none / non-numeric
  - selected_variables:
      x_variable:
      y_variable:
        - date
        - boolean
        - string
        - categorical
    graph_types:
      - name: histogram
        description: Shows the counts of {{y_variable}}.
        optional_variables:
          color_variable:
            types:
              - numeric
              - date
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
  # non-numeric / numeric
  - selected_variables:
      x_variable:
        - boolean
        - string
        - categorical
      y_variable:
        - numeric
    graph_types:
      - name: histogram
        description: Shows the sum of {{y_variable}} across each value of {{x_variable}}.
        optional_variables:
          color_variable:
            types:
              - numeric
              - date
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
      - name: box
        description: Shows the distribution of {{y_variable}} across each value of {{x_variable}}.
        optional_variables:
          color_variable:
            types:
              - numeric
              - date
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
  # numeric / non-numeric
  - selected_variables:
      x_variable:
        - numeric
      y_variable:
        - date
        - boolean
        - string
        - categorical
    graph_types:
      - name: histogram
        description: Shows the sum of {{x_variable}} across each value of {{y_variable}}.
        optional_variables:
          color_variable:
            types:
              - numeric
              - date
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
      - name: box
        description: Shows the distribution of {{x_variable}} across each value of {{y_variable}}.
        optional_variables:
          color_variable:
            types:
              - numeric
              - date
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
      - name: P(Y | X)
        description: Shows the probability of {{y_variable}} given each value of {{x_variable}}.
        optional_variables:
          facet_variable:
            types:
              - boolean
              - string
              - categorical
              - numeric
  # non-numeric / non-numeric
  - selected_variables:
      x_variable:
        - boolean
        - string
        - categorical
      y_variable:
        - boolean
        - string
        - categorical
    graph_types:
      - name: heatmap
        description: Heatmap of the counts of {{x_variable}} and {{y_variable}}.
        optional_variables:
          facet_variable:
            types:
              - boolean
              - string
              - categorical
      - name: P(Y | X)
        description: Shows the probability of {{y_variable}} given each value of {{x_variable}}.
        optional_variables:
          facet_variable:
            types:
              - boolean
              - string
              - categorical
              - numeric
      - name: bar - count distinct
        description: Shows the count of unique values of {{y_variable}} for each {{x_variable}}.
        optional_variables:
          color_variable:
            types:
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - boolean
              - string
              - categorical
  # non-numeric / non-numeric / numeric
  - selected_variables:
      x_variable:
        - boolean
        - string
        - categorical
      y_variable:
        - boolean
        - string
        - categorical
      z_variable:
        - numeric
    graph_types:
      - name: heatmap
        description: Heatmap of the aggregation of {{x_variable}}, {{y_variable}}, and {{z_variable}}.
        optional_variables:
          facet_variable:
            types:
              - boolean
              - string
              - categorical
  # non-numeric / non-numeric / non-numeric
  - selected_variables:
      x_variable:
        - boolean
        - string
        - categorical
      y_variable:
        - boolean
        - string
        - categorical
      z_variable:
        - boolean
        - string
        - categorical
    graph_types:
      - name: heatmap - count distinct
        description: Heatmap showing the count of distinct values of {{z_variable}} for each combination of {{x_variable}}, {{y_variable}}.
        optional_variables:
          facet_variable:
            types:
              - boolean
              - string
              - categorical
  # date / none
  - selected_variables:
      x_variable:
        - date
      y_variable:
    graph_types:
      - name: histogram
        description: Shows the distribution of {{x_variable}}.
        optional_variables:
          color_variable:
            types:
              - date
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
  # date / numeric
  - selected_variables:
      x_variable:
        - date
      y_variable:
        - numeric
    graph_types:
      - name: histogram
        description: Shows the distribution of {{x_variable}}.
        optional_variables:
          color_variable:
            types:
              - date
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
      - name: line
        description: Line graph of {{x_variable}} and the index/order.
        optional_variables:
          color_variable:
            types:
              - numeric
              - date
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
      - name: scatter
        description: Line graph of {{x_variable}} and the index/order.
        optional_variables:
          color_variable:
            types:
              - numeric
              - date
              - boolean
              - string
              - categorical
          size_variable:
            types:
              - numeric
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
      - name: box
        description: Shows the distribution of {{x_variable}}.
        optional_variables:
          color_variable:
            types:
              - date
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - date
              - boolean
              - string
              - categorical
  # date / non-numeric
  - selected_variables:
      x_variable:
        - date
      y_variable:
        - boolean
        - string
        - categorical
    graph_types:
      - name: bar - count distinct
        description: Shows the count of unique values of {{y_variable}} for each {{x_variable}}.
        optional_variables:
          color_variable:
            types:
              - boolean
              - string
              - categorical
          facet_variable:
            types:
              - boolean
              - string
              - categorical
      - name: retention
        description: Shows the retention rate of {{y_variable}} for each cohort in {{x_variable}}.
  # date / date
  - selected_variables:
      x_variable:
        - date
      y_variable:
        - date
    graph_types:
      - name: cohorted conversion rates
        description: Shows the cohorted conversion rates from {{x_variable}} to {{y_variable}} at various durations relative to {{x_variable}}.
        optional_variables:
          facet_variable:
            types:
              - boolean
              - string
              - categorical
      - name: cohorted adoption rates
        description: Shows the cohorted adoption rates from {{x_variable}} to {{y_variable}}.
        optional_variables:
          facet_variable:
            types:
              - boolean
              - string
              - categorical
