# this file defines the different configurations for possible graphs based on the selected columns
configurations:
  - selected_variables:
      x_variable: numeric
      y_variable: None
      color_variable: None
      size_variable: None
      facet_variable: None
    graph_types:
      - boxplot:
          description: Shows the distribution of {x_variable}.
          optional_variables:
            color_variable:
              types:
                - non_numeric
            facet_variable:
              types:
                - non_numeric
      - histogram:
          description: Shows the distribution of {x_variable}.
          optional_variables:
            color_variable:
              types:
                - non_numeric
            facet_variable:
              types:
                - non_numeric
      - scatter:
          description: Shows the relationship between {x_variable} and the index/order.
          optional_variables:
            color_variable:
              types:
                - numeric
                - non_numeric
            size_variable:
              types:
                - numeric
            facet_variable:
              types:
                - non_numeric
      - line:
          description: Line graph of {x_variable} and the index/order.
          optional_variables:
            color_variable:
              types:
                - numeric
                - non_numeric
            size_variable:
              types:
                - numeric
            facet_variable:
              types:
                - non_numeric
  - selected_variables:
      x_variable: numeric
      y_variable: numeric
      color_variable: None
      size_variable: None
      facet_variable: None
    graph_types:
      - scatter:
          description: Shows the relationship between {x_variable} and {y_variable}.
          optional_variables:
            color_variable:
              types:
                - numeric
                - non_numeric
            size_variable:
              types:
                - numeric
            facet_variable:
              types:
                - non_numeric
      - box:
          description: Shows the distribution of {y_variable} values across {x_variable} values.
          optional_variables:
            color_variable:
              types:
                - non_numeric
            facet_variable:
              types:
                - non_numeric
      - histogram:
          description: Shows the distribution of the sum of {y_variable} values across {x_variable} values.
          optional_variables:
            color_variable:
              types:
                - non_numeric
                - numeric
            facet_variable:
              types:
                - non_numeric
