version: '3'
services:
  bash:
    build: .
    working_dir: /code
    volumes:
      - .:/code
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  jupyter:
    build: .
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=d4484563805c48c9b55f75eb8b28b3797c6757ad4871776d
    command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root
