version: '3'
services:
  bash:
    build: .
    working_dir: /code
    volumes:
      - .:/code
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  app:
    build: .
    working_dir: /code/source/entrypoints
    volumes:
      - .:/code
    ports:
      - "8050:8050"
    command: python /code/source/entrypoints/app.py
